### PR TITLE
Switch to CocoaPods

### PR DESCRIPTION
**Pull request by Schemetrical**

### CODE REVIEW

**Comment by Schemetrical** [comment]
My computer sort of broke when I loaded the diffs page so I warn against you doing that :p
I advise that we find a time that we are both online, this might take multiple pushes as I need to do some testing to make sure it works and then push it to the cocoapods trunk.

**Comment by Schemetrical** [comment]
The reason why there are so many lines is because I included the dependencies for every demo. After testing is done, I'll get rid of the preloaded dependencies. Also, I probably have to update README if the users have to manually `pod install`.

**Comment by jdiehl** [comment]
Thanks for putting so much effort in this. However, I do not think it is wise to include the dependencies in the examples (even temporarily) because it blows up the repository. Can you restart the pull request with a clean branch and only include the changes needed to enable pod support? (Do you really need anything besides the file `AsyncNetwork.podspec`?)

**Comment by Schemetrical** [comment]
Much more manageable :-)

**Comment by jdiehl** [comment]
Thanks for your efforts, but this approach is too invasive for my taste.

**Comment by Schemetrical** [comment]
Haha, I see you have done it yourself :). It's much easier managing that way because pods management is device dependent not account. I'll be using this soon, thanks for doing it!

**Comment by jdiehl** [comment]
no problem, and thanks again for your efforts!

**Pull request closed without merging**
