### PR TITLE
Feature/i osx archive

### PR DESCRIPTION
**Pull request by wildthink**

### CODE REVIEW

**Comment by wildthink** [comment]
refactor to use NSArchiver subclasses

**Comment by jdiehl** [comment]
?

**Comment by wildthink** [comment]
Jonathan,

Sorry about that. I forked your project on github and was intending to merge into my own repo but github defaulted to yours for the Pull Request and I didn’t realize it until it was created.

I’m working on a cross platform (iOS to/from OS X) serialization (subclassing NSKeyedArchiver) capability integrated into the AsyncConnection if you’re interested.

Otherwise, my apologies.

Jason

**Comment by jdiehl** [comment]
Sounds really useful. I can add a class method to AsyncConnection to enable using a custom archiver. Would that make your life easier?

**Comment by wildthink** [comment]
That would be a nice, surgical solution that would facilitate my current solution. Although I've been contemplating a more robust solution that I could spike in my fork for your review.

**Pull request closed without merging**
